# Copyright 2021 The Kubermatic Kubernetes Platform contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if eq .Values.serviceGateway.mode "server" }}
{{- if .Values.serviceGateway.server.useCertManger }}

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: service-gw-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: service-gw-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  duration: 43800h # 5 years
  renewBefore: 720h # 30d
  commonName: service-gw-ca
  secretName: service-gw-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: service-gw-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: service-gw-ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: service-gw-ca-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: service-gw-server
  namespace: {{ .Release.Namespace }}
spec:
  duration: 26280h # 3 years
  renewBefore: 720h # 30d
  secretName: service-gw-server-certificates
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
  commonName: service-gw-server
  dnsNames:
  - service-gw-server
  issuerRef:
    name: service-gw-ca-issuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: service-gw-client
  namespace: {{ .Release.Namespace }}
spec:
  duration: 26280h # 3 years
  renewBefore: 720h # 30d
  secretName: service-gw-client-certificates
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - client auth
  commonName: service-gw-client
  dnsNames:
  - service-gw-client
  issuerRef:
    name: service-gw-ca-issuer

{{- end }}
{{- end }}
