apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
  name: kubermatic-fast
provisioner: kubernetes.io/vsphere-volume
parameters:
  diskformat: thin

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
  name: kubermatic-backup
provisioner: kubernetes.io/vsphere-volume
parameters:
  diskformat: thin