apiVersion: v1
kind: Secret
metadata:
  labels:
    job: s3-db-dump-syncer
  name: db-config
stringData:
  env: |-
    export PGDATABASE={{ .Values.s3DBdumpSyncer.db.postgresql.database }}
    export PGHOST={{ .Values.s3DBdumpSyncer.db.postgresql.host }}
    export PGOPTIONS={{ .Values.s3DBdumpSyncer.db.postgresql.options }}
    export PGPORT={{ .Values.s3DBdumpSyncer.db.postgresql.port }}
    export PGUSER={{ .Values.s3DBdumpSyncer.db.postgresql.user }}
    export PGPASSWORD={{ .Values.s3DBdumpSyncer.db.postgresql.pw }}
    export DB_DUMP_NAME={{ .Values.s3DBdumpSyncer.db.dumper.filename }}
