apiVersion: v1
kind: Secret
metadata:
  labels:
    job: s3-db-dump-syncer
  name: s3-config
stringData:
  env: |-
    export TARGET_URL={{ required "A valid .Values.s3DBdumpSyncer.s3.target.url entry required!" .Values.s3DBdumpSyncer.s3.target.url }}
    export TARGET_BUCKET={{ .Values.s3DBdumpSyncer.s3.target.bucket }}
    export TARGET_SSL_VERIFY_FLAG={{ if eq .Values.s3DBdumpSyncer.s3.target.insecure_skip_verify true }}--no-verify-ssl{{- end }}
    export TARGET_RENAME_CHAR={{ .Values.s3DBdumpSyncer.s3.target.renameChar }}
  credentials: |
    [target]
    aws_access_key_id={{ required "A valid .Values.s3DBdumpSyncer.s3.target.accessKey entry required!" .Values.s3DBdumpSyncer.s3.target.accessKey }}
    aws_secret_access_key={{ required "A valid .Values.s3DBdumpSyncer.s3.target.secretKey entry required!" .Values.s3DBdumpSyncer.s3.target.secretKey }}
    {{- if .Values.s3DBdumpSyncer.s3.target.ca_bundle }}
    ca_bundle=~/.aws/ca_bundle_target.pem
    {{- end }}
{{- if .Values.s3DBdumpSyncer.s3.target.ca_bundle }}
  ca_bundle_target.pem: |-
{{ .Values.s3DBdumpSyncer.s3.target.ca_bundle | indent 4 }}
{{- end }}
