apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nutanix-exporter.fullname" . }}-config
  labels:
    app: {{ template "nutanix-exporter.name" . }}
    chart: {{ template "nutanix-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
  config.yaml: |
{{ if empty .Values.config -}}
{{- fail ".Values.config is required! Refer to https://github.com/claranet/nutanix-exporter" -}}
{{- else -}}
{{ toYaml .Values.config | indent 4 }}
{{- end }}
