apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/fluxcd/flux2/manifests/install?ref=v0.24.0

images:
  - name: fluxcd/helm-controller
    newName: '{{ Registry "ghcr.io" }}/fluxcd/helm-controller'
  - name: fluxcd/image-automation-controller
    newName: '{{ Registry "ghcr.io" }}/fluxcd/image-automation-controller'
  - name: fluxcd/image-reflector-controller
    newName: '{{ Registry "ghcr.io" }}/fluxcd/image-reflector-controller'
  - name: fluxcd/kustomize-controller
    newName: '{{ Registry "ghcr.io" }}/fluxcd/kustomize-controller'
  - name: fluxcd/notification-controller
    newName: '{{ Registry "ghcr.io" }}/fluxcd/notification-controller'
  - name: fluxcd/source-controller
    newName: '{{ Registry "ghcr.io" }}/fluxcd/source-controller'
namespace: flux-system
patches:
  - path: patches/add-node-selector.yaml
    target:
      kind: Deployment
transformers:
  - transformers/label-transformer.yaml 
