replicaCount: 1

config: {}
  # default:
  #   nutanix_host: https://127.0.0.1:9440
  #   nutanix_user: admin
  #   nutanix_password: adminpassword


podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9405"
  prometheus.io/path: "/metrics"

image:
  repository: claranet/nutanix-exporter
  tag: v0.5.1
  pullPolicy: IfNotPresent

service:
  enabled: false
  type: ClusterIP
  port: 9405
  targetport: 9405

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# Set the container security context
securityContext:
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

# Set the Pod security context
podSecurityContext: {}
  #  fsGroup: 65532
