---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aws-priv-ip-enforce-seed-cluster-controller
  name: aws-priv-ip-enforce-seed-cluster-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-priv-ip-enforce-seed-cluster-controller
  strategy: {}
  template:
    metadata:
      labels:
        app: aws-priv-ip-enforce-seed-cluster-controller
    spec:
      serviceAccountName: machine-controller
      terminationGracePeriodSeconds: 5
      containers:
      - image: quay.io/kubermatic/util:1.1.2
        name: util
        command:
        - bash
        - -c
        - |
          ltmp=$(mktemp -d) ; trap "rm -rv $ltmp" EXIT

          # syncrun to update every md in the seed
          syncrun() {
            echo "start syncrun: $(date)"
            kubectl get -n kube-system -o json machinedeployments \
               | jq -r '.items[]|select(.spec.template.spec.providerSpec.value.cloudProviderSpec.assignPublicIP != false) .metadata.name' \
              > $ltmp/machinedeployments

            while read -r md; do
              echo "Found machinedeployment $md with assignment of public IP's. Setting 'assignPublicIP=false'"

              kubectl patch -n kube-system machinedeployment $md --type=json -p='
              - op: replace
                path: /spec/template/spec/providerSpec/value/cloudProviderSpec/assignPublicIP
                value: false
              '
            done < $ltmp/machinedeployments
          }

          while true; do
          syncrun
          sleep 5
          done
        resources:
          requests:
            cpu: 10m
            memory: 200M
          limits:
            cpu: 50m
