apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    job: s3-syncer
  name: s3-syncer
data:
  env: |-
    export SOURCE_URL={{ required "A valid .Values.s3syncer.source.url entry required!" .Values.s3syncer.source.url }}
    export SOURCE_BUCKET={{ .Values.s3syncer.source.bucket }}
    export SOURCE_SSL_VERIFY_FLAG={{ if eq .Values.s3syncer.source.insecure_skip_verify true }}--no-verify-ssl{{- end }}
    export TARGET_URL={{ required "A valid .Values.s3syncer.target.url entry required!" .Values.s3syncer.target.url }}
    export TARGET_BUCKET={{ .Values.s3syncer.target.bucket }}
    export TARGET_SSL_VERIFY_FLAG={{ if eq .Values.s3syncer.target.insecure_skip_verify true }}--no-verify-ssl{{- end }}
    export TARGET_RENAME_CHAR={{ .Values.s3syncer.target.renameChar }}
  credentials: |
    [source]
    aws_access_key_id={{ required "A valid .Values.s3syncer.source.accessKey entry required!" .Values.s3syncer.source.accessKey }}
    aws_secret_access_key={{ required "A valid .Values.s3syncer.source.secretKey entry required!" .Values.s3syncer.source.secretKey }}
    {{- if .Values.s3syncer.source.ca_bundle }}
    ca_bundle=~/.aws/ca_bundle_source.pem
    {{- end }}
    [target]
    aws_access_key_id={{ required "A valid .Values.s3syncer.target.accessKey entry required!" .Values.s3syncer.target.accessKey }}
    aws_secret_access_key={{ required "A valid .Values.s3syncer.target.secretKey entry required!" .Values.s3syncer.target.secretKey }}
    {{- if .Values.s3syncer.target.ca_bundle }}
    ca_bundle=~/.aws/ca_bundle_target.pem
    {{- end }}

{{- if .Values.s3syncer.source.ca_bundle }}
  ca_bundle_source.pem: |-
{{ .Values.s3syncer.source.ca_bundle | indent 4 }}
{{- end }}
{{- if .Values.s3syncer.target.ca_bundle }}
  ca_bundle_target.pem: |-
{{ .Values.s3syncer.target.ca_bundle | indent 4 }}
{{- end }}
