{{- if .Values.s3syncer.target.azuregateway.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-key
  labels:
    app: minio-azure-gateway
type: Opaque
data:
  key: {{ .Values.s3syncer.target.azuregateway.azureStorageKey | b64enc | quote }}
{{- end }}
