{{- if not .Values.vmware-exporter.vsphere.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vmware-exporter.fullname" . }}-secret
  labels:
    app: {{ template "vmware-exporter.name" . }}
    chart: {{ template "vmware-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  VSPHERE_PASSWORD: {{ default "" .Values.vmware-exporter.vsphere.password | b64enc | quote }}
{{- range $section := .Values.vmware-exporter.vsphere.sections }}
{{- $key := $section.name }}
  VSPHERE_{{ $key }}_PASSWORD: {{ $section.password | b64enc | quote }}
{{- end }}
{{- end }}
