{{- if .Values.vmware-exporter.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "vmware-exporter.fullname" . }}
  labels:
    app: {{ template "vmware-exporter.name" . }}
    chart: {{ template "vmware-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.vmware-exporter.service.annotations }} 
  annotations: 
{{ toYaml . | indent 4 }} 
{{- end }} 
spec:
  type: {{ .Values.vmware-exporter.service.type }}
  ports:
    - port: {{ .Values.vmware-exporter.service.port }}
      targetPort: {{ .Values.vmware-exporter.service.targetport }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "vmware-exporter.name" . }}
    release: {{ .Release.Name }}
{{- end }}
