# Example of an ApplicationDefinition
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: eclipse-che
spec:
  description: A Helm chart for deploying Eclipse Che on a Kubernetes or Openshift cluster.
  method: helm
  versions:
  - template:
      source:
        helm:
          chartName: eclipse-che
          chartVersion: 7.53.0
          url: https://eclipse-che.github.io/che-operator/charts
    version: 7.53.0
