# Example of an ApplicationDefinition
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: harbor
spec:
  description: Harbor is an open source trusted cloud native registry project that stores, signs, and scans content.
  method: helm
  versions:
  - template:
      source:
        helm:
          chartName: harbor
          chartVersion: 1.10.0
          url: https://helm.goharbor.io
    version: 2.6.0
