apiVersion: v1
data:
  ## On first install only
  #kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)" -o yaml --dry-run
  secretkey: TODO-REPLACE
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
