apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - resources/namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.7/manifests/ha/install.yaml

patchesStrategicMerge:
  - patches/delete-dynamic-configmaps.yaml
  - patches/add-configmap-init-container.yaml